# Generated by Django 5.1.3 on 2024-11-22 15:11

import django.db.models.deletion
import django.utils.timezone
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('employee_id', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(default='', max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(default='', max_length=10)),
                ('phone_number', models.IntegerField()),
                ('specialization', models.CharField(default='', max_length=20)),
                ('department', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('patient_id', models.IntegerField(unique=True)),
                ('age', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(default='', max_length=10)),
                ('phone_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('employee_id', models.IntegerField(unique=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(default='', max_length=10)),
                ('phone_number', models.IntegerField()),
                ('position', models.CharField(default='', max_length=20)),
                ('department', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OutPatientRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.IntegerField(editable=False, unique=True)),
                ('reason_for_visit', tinymce.models.HTMLField(default='', max_length=10000)),
                ('sickness', tinymce.models.HTMLField(default='', max_length=10000)),
                ('diagnosis', tinymce.models.HTMLField(default='', max_length=10000)),
                ('medication', tinymce.models.HTMLField(default='', max_length=10000)),
                ('payment_method', models.CharField(default='', max_length=20)),
                ('next_of_kin_name', models.CharField(default='', max_length=20)),
                ('next_of_kin_contact', models.IntegerField()),
                ('next_of_kin_address', models.IntegerField()),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assigned_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.patient', to_field='patient_id')),
            ],
        ),
        migrations.CreateModel(
            name='InPatientRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.IntegerField(editable=False, unique=True)),
                ('reason_for_visit', tinymce.models.HTMLField(default='', max_length=10000)),
                ('sickness', tinymce.models.HTMLField(default='', max_length=10000)),
                ('diagnosis', tinymce.models.HTMLField(default='', max_length=10000)),
                ('medication', tinymce.models.HTMLField(default='', max_length=10000)),
                ('payment_method', models.CharField(default='', max_length=20)),
                ('room_no', models.IntegerField(unique=True)),
                ('next_of_kin_name', models.CharField(default='', max_length=20)),
                ('next_of_kin_contact', models.IntegerField()),
                ('next_of_kin_address', models.IntegerField()),
                ('date_addmitted', models.DateTimeField()),
                ('date_discharged', models.DateTimeField()),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assigned_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.patient', to_field='patient_id')),
            ],
        ),
    ]
