# Generated by Django 5.1.3 on 2024-11-29 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0002_patientprofile_total_appointments_and_more'),
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='password',
        ),
        migrations.AlterField(
            model_name='inpatientrecord',
            name='assigned_doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acc.institutiondoctorprofile'),
        ),
        migrations.AlterField(
            model_name='outpatientrecord',
            name='assigned_doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acc.institutiondoctorprofile'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.CharField(default='', max_length=200),
        ),
    ]
