# Generated by Django 5.1.3 on 2024-12-01 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0001_initial'),
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorappointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acc.institutiondoctorprofile'),
        ),
    ]
