# Generated by Django 5.1.3 on 2024-11-23 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_doctorappointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
