# Generated by Django 5.1.3 on 2024-11-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_remove_doctor_date_of_birth_remove_doctor_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='employee_id',
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='employee_id',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
