# Generated by Django 5.1.3 on 2024-11-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0003_alter_doctor_employee_id_alter_staff_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inpatientrecord',
            name='record_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='outpatientrecord',
            name='record_id',
            field=models.IntegerField(unique=True),
        ),
    ]
