# Generated by Django 5.1.3 on 2024-11-29 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0004_alter_inpatientrecord_record_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorappointment',
            name='institution',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='inpatientrecord',
            name='institution',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='outpatientrecord',
            name='institution',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='patient',
            name='institution',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='staff',
            name='institution',
            field=models.CharField(default='', max_length=200),
        ),
    ]
