# Generated by Django 5.1.3 on 2024-11-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0005_doctorappointment_institution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='institution',
            field=models.CharField(default='', max_length=200),
        ),
    ]
