from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.
class CustomUser(AbstractUser):
    USER_TYPE_CHOICES = (
        ('patient', 'Patient'),
        ('doctor', 'Doctor'),
        ('institution', 'Institution'),
    )
    user_type = models.CharField(max_length=20, choices=USER_TYPE_CHOICES)
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=150, unique=True)
    institution = models.CharField(max_length=10000, default='Private')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username',]

    class Meta:
        verbose_name_plural ='Users'

    def __str__(self):
        return self.username

class DoctorProfile(models.Model):
    doctor = models.CharField(unique=True, max_length=200)
    date_of_birth = models.DateField(default='2024-11-29')
    gender = models.CharField(default='', max_length=10)
    phone_number = models.IntegerField(default=0)
    specialization = models.CharField(default='', max_length=20)
    license_no = models.IntegerField(default=0)
    profile = models.ImageField(upload_to='doctors/')
    total_appointments = models.PositiveIntegerField(default=0)
    total_patients = models.PositiveIntegerField(default=0)
    total_reports = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f'{self.doctor}'

class InstitutionDoctorProfile(models.Model):
    doctor = models.CharField(unique=True, max_length=200)
    institution = models.CharField(default='', max_length=100)
    employee_id = models.CharField(unique=True, max_length=7) # autogenerated
    email = models.EmailField(unique=True)
    date_of_birth = models.DateField(null=True)
    gender = models.CharField(default='', max_length=10)
    phone_number = models.IntegerField(null=True)
    specialization = models.CharField(default='', max_length=20, null=True)
    department = models.CharField(default='', max_length=20, null=True)
    total_appointments = models.PositiveIntegerField(default=0)
    total_patients = models.PositiveIntegerField(default=0)
    total_reports = models.PositiveIntegerField(default=0)
    total_patients_treated = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f'{self.doctor}'

class PatientProfile(models.Model):
    patient = models.CharField(unique=True, max_length=200)
    date_of_birth = models.DateField(default='2024-11-29')
    gender = models.CharField(default='', max_length=10)
    phone_number = models.IntegerField(default=0)
    adress = models.CharField(default='', max_length=20)
    emergency_contact_name = models.CharField(default='', max_length=20)
    emergency_contact_number = models.IntegerField(default=0)
    profile = models.ImageField(upload_to='patients/')
    total_appointments = models.PositiveIntegerField(default=0)
    total_visits = models.PositiveIntegerField(default=0)
    
    def __str__(self):
        return f'{self.patient}'

class InstitutionProfile(models.Model):
    institution = models.CharField(unique=True, max_length=200)
    registration_number = models.CharField(max_length=100, unique=True)  # Unique ID for institution
    address = models.TextField()
    city = models.CharField(max_length=100, default='')
    state = models.CharField(max_length=100, default='')
    country = models.CharField(max_length=100, default='')
    phone_number = models.CharField(max_length=15, default='')
    email = models.EmailField(unique=True)
    website = models.URLField(blank=True, null=True)
    established_date = models.DateField(default='2024-11-29')
    total_doctors = models.PositiveIntegerField(default=0) 
    total_patients = models.PositiveIntegerField(default=0) 
    total_staff = models.PositiveIntegerField(default=0)  
    total_employees = models.PositiveIntegerField(default=0) # doctors + staff  
    description = models.TextField(blank=True, null=True)

    # Audit Fields
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.institution