# Generated by Django 5.1.3 on 2024-11-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='institution',
            field=models.CharField(default='Private', max_length=10000),
        ),
    ]
