# Generated by Django 5.1.3 on 2024-12-01 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutiondoctorprofile',
            name='total_patients_treated',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
