# Generated by Django 5.1.3 on 2024-11-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='total_appointments',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='total_doctors',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='total_profile_visits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
