# Generated by Django 5.1.3 on 2024-11-27 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0002_customuser_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='total_appointments',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='total_patients',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='total_reports',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
