# Generated by Django 5.1.3 on 2024-11-29 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0002_patientprofile_total_appointments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionprofile',
            name='institution',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
