# Generated by Django 5.1.3 on 2024-12-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0002_institutiondoctorprofile_total_patients_treated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='doctor',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='patient',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
