# Generated by Django 5.1.3 on 2024-12-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0003_alter_doctorprofile_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='date_of_birth',
            field=models.DateField(default='2024-11-29'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='license_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='phone_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='date_of_birth',
            field=models.DateField(default='2024-11-29'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='phone_number',
            field=models.IntegerField(default=0),
        ),
    ]
