# Generated by Django 5.1.3 on 2024-11-29 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0003_alter_institutionprofile_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionprofile',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='institutionprofile',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='institutionprofile',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='institutionprofile',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
    ]
