# Generated by Django 5.1.3 on 2024-11-29 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0004_alter_institutionprofile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionprofile',
            name='established_date',
            field=models.DateField(default='2024-11-29'),
        ),
    ]
