# Generated by Django 5.1.3 on 2024-12-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0004_alter_doctorprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientprofile',
            old_name='total_doctors',
            new_name='total_visits',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='total_profile_visits',
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='emergency_contact_number',
            field=models.IntegerField(default=0),
        ),
    ]
