# Generated by Django 5.1.3 on 2024-12-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0005_rename_total_doctors_patientprofile_total_visits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='profile',
            field=models.ImageField(default='profile.png', upload_to='doctors/'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='profile',
            field=models.ImageField(default='profile.png', upload_to='patients/'),
        ),
    ]
