# Generated by Django 5.1.3 on 2024-11-30 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0005_alter_institutionprofile_established_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionprofile',
            name='total_employees',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='total_staff',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='institutiondoctorprofile',
            name='doctor',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
