# Generated by Django 5.1.3 on 2024-11-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0006_institutionprofile_total_employees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutiondoctorprofile',
            name='employee_id',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
