# Generated by Django 5.1.3 on 2024-11-30 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0007_alter_institutiondoctorprofile_employee_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institutiondoctorprofile',
            old_name='name',
            new_name='institution',
        ),
    ]
